---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  - wireguard-config-secret.yaml
namespace: "wireguard"
namePrefix: "wireguard-"
images:
  - name: "weejewel/wg-easy"
    newTag: "latest"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
  - name: secret-sentinel
    files:
      - "wireguard-config-secret.yaml"
