---
apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-svc
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.20.6
spec:
  type: LoadBalancer
  ports:
    - name: wireguard
      port: 51820
      targetPort: listen
      protocol: UDP
